### ISSUE TITLE
Исполняемый файл для MacOS

### ISSUE THREAD

**Issue by Bramfoxie** [KruFFT/wxCAN-Sniffer#1]
Если есть возможность, создайте исполняемый (аля *.exe) файл для MacOS. Уже несколько дней бьюсь, не получается скомпилировать из исходников.

**Comment by KruFFT** [comment]
У меня нет, в обозримом пространстве, ни одного устройства с MacOS. А код и не будет компилироваться, так как надо переписывать код работы с последовательным портом. Он чисто под WinAPI написан. Такое даже на Linux не собирается, там тоже требуется переписывать код работы с последовательным портом.

**Comment by KruFFT** [comment]
Устройств с MacOS так и не появилось.
