### ISSUE TITLE
Some misunderstandings 

### ISSUE THREAD

**Issue by Kabron287** [KruFFT/wxCAN-Sniffer#3]
Мое почтение. 
Удалось повторить ваш проект на ESP32 с библиотекой github.com/sandeepmistry/arduino-CAN и даже скомпилировать exe. 
Однако:
1. совсем не понятны назначения ячеек справа от кнопки Подключить/Отключить.
2. отсутствуют счетчики пакетов.
Я попытался разобраться в исходниках и понял, что это не мое.
Попробовал wxFormBuilder, но ему нечего взять в проекте. 
Как можно редактировать этот GUI в VS или где либо еще?

Заранее благодарен

**Comment by Kabron287** [comment]
ОК это FPS и BPS

**Comment by KruFFT** [comment]
Добрый день.

1. Да, всё верно, это скорость кадров и потока байтов в секунду. В статье об этом написано.
2. Я перестал использовать внешние редакторы окон для проектов wxWidgets после того, как понял подход с вёрсткой элементов через wxSizer. По началу это кажется сложным, но когда понимаешь - это становится похоже на вёрстку в Android с LinearLayout, они схожи. Либо можно использовать обратный подход: набрасываем элементы в wxFormBuilder и в нём же смотрим сгенерированный им С++ код.

Поэтому редактирование GUI этого приложения придётся вести вручную, все элементы "расставляются" в конструкторе формы в файле FormMain.cpp. Я постарался снабдить всё это комментариями, но всё равно, без хорошего понимания wxSizer будет не очевидно.

**Comment by Kabron287** [comment]
Т.е. надо с нуля повторить Вашу форму и дальше ее модифицировать?

**Comment by KruFFT** [comment]
Тут зависит от того, что необходимо:
1. Если необходимо добавить какой-то новый элемент или убрать - то можно просто в коде его описать, как я сделал в [этом](https://github.com/KruFFT/wxCAN-Sniffer/commit/fdcd48cbf1c5ca2575880ca21bff09f895ce89eb) коммите для файлов FormMain.h (22, 57 и 103 строки) и FormMain.cpp (19, 213..216, 706..711, 757).
2. Если необходимо сделать что-то своё с чистого листа - то тут уже как будет удобнее, можно кодом описать, можно результат wxFormBuilder подключить.
