### ISSUE TITLE
How to connect via WIFI?

### ISSUE THREAD

**Issue by DJAGER47** [KruFFT/wxCAN-Sniffer#4]
На могу понять как подключиться по Wi-FI к программе?
Пытаюсь разобраться в теме CAN и мне показался ваш проект очень интересным. На основе его хочу сделать охлаждение батарей у гибридов toyota

**Comment by KruFFT** [comment]
Добрый день.
При использовании Wi-Fi для связи между программой на компьютере и в ESP:
1. В коде программы ESP указаны: название точки доступа и пароль к ней. Компьютер необходимо подключить в эту сеть.
2. После запуска приложения на РС, произойдёт автоматическое соединение, так как приложение при старте автоматически открывает порт для прослушивания сообщений, а ESP, при настройке на работу через Wi-Fi автоматически будет отправлять пакеты в сеть, как только получит из CAN-сети автомобиля.

**Comment by KruFFT** [comment]
Думаю, что не актуально уже.
