### ISSUE TITLE
CAN sniffer (stm32+mcp2551)

### ISSUE THREAD

**Issue by nvumnov** [KruFFT/wxCAN-Sniffer#5]
Здравствуйте, пытаюсь повторить ваш проект, только сам сниффер собран на stm32 и mcp2551.
В мониторе com порта в Arduino сниффер отправляет данные из can шины.
Вот такого формата:
"439893; 188; 6; 46; 0; 0; 0; 0; 0; 0; 0
439894; 2B0; 8; 46; C; 0; A; 0; 0; 0; 0
439895; 4E8; 7; 46; 0; 0; 0; 0; 0; 0; 0
439898; 4EE; 4; 46; 0; 0; 0; FF; FF; FF; FF
439902; 683; 3; 46; 0; 82; 0; 0; 0; 0; 0
439943; 506; 8; 16; 0; 42; 16; 81; 0; 2; 0
440041; 501; 8; 61; 0; 42; 6; 1; 0; 40; 1"
время; ID; длинна; и 8 ячеек данных.
Пытаюсь подружить сниффер с программой wxCAN-sniffer, не получается.
Добавлял сигнатуру 0x55AA55AA, тоже не хочет.
В программировании не силен, но что-то получается.
Подскажите в каком месте поправить.
[sniffer.ino.txt](https://github.com/KruFFT/wxCAN-Sniffer/files/10481581/sniffer.ino.txt)
Скомпилировать программу получилось (спасибо за видео), может в программе wxCAN-sniffer надо что-то поправить.
Я так понимаю, программа к com порту подключается, только не совпадает формат сообщений из com порта.

**Comment by KruFFT** [comment]
Добрый день.
Формат пакета данных не совпадает. К тому же, временной интервал между пакетами был добавлен только начиная с версии 2.1.0. Формат передаваемых данных описан в файле Common.h:

`// CAN-пакет для отправки данных`
`#pragma pack (push, 1)`
`struct CANFrame`
`{`
`public:`
`	uint32_t id;		// идентификатор пакета`
`	uint16_t interval;	// интервал между пакетами (мс)`
`	uint8_t  length;	// длина пакета`
`	uint8_t  data[8];	// массив данных пакета, до 8 байт`
`};`
`#pragma pack(pop)`

Перед этим пакетом должна быть сигнатура, которая тоже описана в этом файле, немного выше.

Если вам необходимо адаптировать под свой пакет, то его надо описать как в коде для микроконтроллера, так и в коде программы для компьютера. Просто расставьте необходимые поля в нужном вам порядке.
