### ISSUE TITLE
Логика построения графика

### ISSUE THREAD

**Issue by Dragon-Knight** [KruFFT/wxCAN-Sniffer#6]
Как я понял, программа парсит выбранную ячейку + 1 и преобразует это в `uint16_t`.
Было бы не плохо сделать возможность выбирать в чего парсим: `int8, uint8, int16, uint16, int24, uint24, int32, uint32, float, double`, а так-же в табличке обводить какие именно байты именно мы анализируем.

В Си и С++ я могу, но Шарп и тем более wxWidgets для меня очень странные штуки..

**Comment by KruFFT** [comment]
Подумаю над этим, пока не было необходимости в таком.

wxWidgets используется всего лишь для окошек и кнопочек. Код весь на чистом C++.

**Comment by KruFFT** [comment]
Добавлено в версии [2.3.0](https://github.com/KruFFT/wxCAN-Sniffer/releases).
